services:
  kerberos-kdc:
    build:
      context: ./kerberos-kdc
      dockerfile: Dockerfile
    container_name: kerberos-kdc
    hostname: kerberos-kdc
    ports:
      - "749:749"
      - "88:88/udp"

  client-server:
    build:
      context: ./client-server
      dockerfile: Dockerfile
    container_name: client-server
    hostname: client-server
    stdin_open: true
    tty: true
    depends_on:
      - kerberos-kdc

  service-server:
    build:
      context: ./service-server
      dockerfile: Dockerfile
    container_name: service-server
    hostname: service-server
    ports:
      - "2222:22"
    depends_on:
      - kerberos-kdc

networks:
  kerberos-net:
    driver: bridge
